$Env:DB_URL = "https://attendance-by-face-7de0b-default-rtdb.firebaseio.com/"
$Env:STR_URL = "attendance-by-face-7de0b.appspot.com"
$Env:TEMPLATE = "D:\\dulieuD\\Program Language\\Computer_Vision\\FinalExam\\attendance-by-face\\static\\template2.png"
$Env:CERD = "D:\\dulieuD\\Program Language\\Computer_Vision\\FinalExam\\attendance-by-face\\serviceAccountKey.json"
$Env:BACKGROUND = "D:\\dulieuD\\Program Language\\Computer_Vision\\FinalExam\\attendance-by-face\\static\\background.jpg"